#pragma once

#include "DataParser.hpp"
#include "StepOne.hpp"
#include "StepTwo.hpp"
#include "StepThree.hpp"

#include <wx/event.h>
#include <wx/clipbrd.h>
#include <wx/frame.h>
#include <wx/progdlg.h>
#include <wx/wx.h>
#include <wx/wizard.h>

#include <filesystem>
#include <future>
#include <format>
#include <chrono>
#include <thread>
#include <string>
#include <string_view>

class Launcher : public wxApp
{
public:
    bool OnInit() override;
};

class CrimeApp : public wxFrame
{
public:
    CrimeApp();
};

class CrimeWizard : public wxWizard
{
public:
    CrimeWizard(wxFrame* parent);

    wxWizardPage* GetFirstPage() const { return m_pageOne; }

private:
    // Return codes expected from the Python geoprocessing script.
    enum ReturnCode
    {
        Success,
        SignInFailed,
        CSVnotFound,
        URLerrorDeleteFeatures,
        URLerrorAppendFeatures,
        UserClosedWindow = -1073741510, // Received if user closed window.
    };

    wxWizardPageSimple* m_pageOne;
    wxWizardPageSimple* m_pageTwo;
    wxWizardPageSimple* m_pageThree;

    void callPython(std::promise<int> promise, const std::string pythonPath) const;
    int uploadGISdata();
    void help(wxWizardEvent& event);
    void nextClicked(wxWizardEvent& event);
    std::string translate(int returnCode) const;

    wxDECLARE_EVENT_TABLE(); // To catch the event generated by the help button.
};